---
# This Playbook Install Docker (Only For CentOS 7)

  - name: Install SoftWare For CentOS 7
    yum: name={{ item }} state=latest
    with_items:
      - yum-utils
      - lvm2
      - device-mapper-persistent-data

  - name: Upload Docker REPO For CentOS
    copy: src=docker.repo dest=/etc/yum.repos.d/

  - name: Install Docker For CentOS
    yum: name=docker-engine-* state=present

  - name: Configure Docker 
    copy: src=docker.service dest=/usr/lib/systemd/system/    

  - name: Start Docker
    service: name=docker state=restarted enabled=yes
